version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: spring-rest-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring-rest-db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    profiles:
      - all

  back-end:
    image: laminba2003/spring-rest:0.0.1-SNAPSHOT
    container_name: spring-rest-backend
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/spring-rest-db?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
      spring.datasource.username: user
      spring.datasource.password: user
      spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://keycloak:8080/realms/training/protocol/openid-connect/certs
      spring.cache.type: redis
      spring.redis.host: redis
      spring.redis.port: 6379
      JAVA_TOOL_OPTIONS: -Xss256K -XX:ReservedCodeCacheSize=64M -XX:MaxMetaspaceSize=128M -Xms512M -Xmx1g
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
      - keycloak
    profiles:
      - all

  redis:
    image: redis:5.0.3-alpine
    container_name: spring-rest-redis
    ports:
      - 6379:6379
    profiles:
      - all

  postgres:
    image: postgres:9.6
    container_name: spring-rest-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: bitnami/keycloak:18.0.0-debian-11-r0
    container_name: spring-rest-keycloak
    environment:
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_DATABASE_PASSWORD: password
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - 8080:8080
    depends_on:
      - postgres

  maildev:
    container_name: spring-rest-maildev
    image: djfarrelly/maildev:1.0.0-rc2
    ports:
      - 9999:80
      - 25

volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local