spring:
    datasource:
        password: passer
        url: jdbc:mysql://localhost:3306/example?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        jpa:
            database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost/auth/realms/training/protocol/openid-connect/certs


logging:
    config: classpath:log4j2-dev.xml