server:
    port: 9090
spring:
    application:
        name: spring-training
    mvc:
      throw-exception-if-no-handler-found: true
    liquibase:
        change-log: classpath:/db/changelog/changelog-master.xml

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,wavefront
    info:
        env:
            enabled: true

info:
    application:
        name: spring-training
        version: '@project.version@'