server:
    port: 9090
    servlet:
      context-path: /v1
spring:
    application:
        name: spring-training
    liquibase:
        change-log: classpath:/db/changelog/changelog-master.xml

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,wavefront
    info:
        env:
            enabled: true

info:
    application:
        name: spring-training
        version: '@project.version@'