server:
  port: 9093

spring:
  application:
    name: spring-training
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,wavefront
  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: ALWAYS

  health:
    redis:
      enabled: false
    probes:
      enabled: true

info:
  application:
    name: Spring Rest
    description: Simple SpringBoot Rest application

wavefront:
  application:
    name: spring-training


cors:
  allowCredentials: true
  allowedOriginPattern: "*"
  allowedHeaders:
    - "*"
  allowedMethods:
    - GET
    - POST
    - PUT
    - DELETE
    - PUT
    - OPTIONS
    - PATCH
    - DELETE
