spring:
    datasource:
        password: user
        url: jdbc:mysql://localhost:3307/spring-training?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
        username: user
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      open-in-view: false
      hibernate:
        use-new-id-generator-mappings: false
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:8080/realms/training/protocol/openid-connect/certs


logging:
    config: classpath:log4j2-dev.xml