apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  management.metrics.export.wavefront.uri: https://wavefront.surf
  spring.datasource.url: {{ .Values.api.configuration.datasource.url }}
  spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  spring.security.oauth2.resourceserver.jwt.issuer-uri: {{ .Values.api.configuration.jwt.issuer }}
  spring.security.oauth2.resourceserver.jwt.jwk-set-uri: {{ .Values.api.configuration.jwt.jwk }}
  management.health.probes.enabled: "true"