apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-secret
data:
  management.metrics.export.wavefront.api-token: {{ .Values.api.configuration.wavefront.token }}
  spring.datasource.username: {{ .Values.api.configuration.datasource.username }}
  spring.datasource.password: {{ .Values.api.configuration.datasource.password }}
type: Opaque