apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "deployment.fullname" . }}
data:
  management.metrics.export.wavefront.api-token: {{ .Values.api.configuration.wavefront.token }}
  spring.datasource.username: {{ .Values.api.configuration.datasource.username }}
  spring.datasource.password: {{ .Values.api.configuration.datasource.password }}
  spring.redis.password: {{ .Values.api.configuration.redis.password }}
type: Opaque